### ISSUE TITLE
Fails to install from NPM

### ISSUE THREAD

**Issue by danPixl** [leo60228/leowiki#3]
Output of command `npm install leowiki`
```
npm ERR! Linux 3.13.0-100-generic
npm ERR! argv "/home/blaze/.nvm/versions/node/v6.9.1/bin/node" "/home/blaze/.nvm/versions/node/v6.9.1/bin/npm" "update"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! leowiki@1.0.2 install: `require-self`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the leowiki@1.0.2 install script 'require-self'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leowiki package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     require-self
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leowiki
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leowiki
npm ERR! There is likely additional logging output above.
```

Log:
```
6138 silly install leowiki@1.0.2 /home/blaze/Starkit/Creamsicle/node_modules/.staging/leowiki-4d4ea277
6139 info lifecycle leowiki@1.0.2~install: leowiki@1.0.2
6140 verbose lifecycle leowiki@1.0.2~install: unsafe-perm in lifecycle true
6141 verbose lifecycle leowiki@1.0.2~install: PATH: /home/blaze/.nvm/versions/node/v6.9.1/lib/node_modules/npm/bin/node-gyp-bin:/home/blaze/Starkit/Creamsicle/node_modules/leowiki/node_modules/.bin:/home/blaze/Starkit/Creamsicle/node_modules/.bin:/home/blaze/.nvm/versions/node/v6.9.1/bin:/home/blaze/.linuxbrew/bin:/home/blaze/.rvm/gems/ruby-2.3.0/bin:/home/blaze/.rvm/gems/ruby-2.3.0@global/bin:/home/blaze/.rvm/rubies/ruby-2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/blaze/.rvm/bin:/home/blaze/.rvm/bin:/home/blaze/.rvm/bin
6142 verbose lifecycle leowiki@1.0.2~install: CWD: /home/blaze/Starkit/Creamsicle/node_modules/leowiki
6143 silly lifecycle leowiki@1.0.2~install: Args: [ '-c', 'require-self' ]
6144 info lifecycle leowiki@1.0.2~install: Failed to exec install script
6145 verbose unlock done using /home/blaze/.npm/_locks/staging-11bcf025d597f4f6.lock for /home/blaze/Starkit/Creamsicle/node_modules/.staging
6146 silly rollbackFailedOptional Starting
6147 silly rollbackFailedOptional Finishing
6148 silly runTopLevelLifecycles Finishing
6149 silly install printInstalled
6150 verbose stack Error: leowiki@1.0.2 install: `require-self`
6150 verbose stack spawn ENOENT
6150 verbose stack     at ChildProcess.<anonymous> (/home/blaze/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/utils/spawn.js:33:16)
6150 verbose stack     at emitTwo (events.js:106:13)
6150 verbose stack     at ChildProcess.emit (events.js:191:7)
6150 verbose stack     at maybeClose (internal/child_process.js:877:16)
6150 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
6151 verbose pkgid leowiki@1.0.2
6152 verbose cwd /home/blaze/Starkit/Creamsicle
6153 error Linux 3.13.0-100-generic
6154 error argv "/home/blaze/.nvm/versions/node/v6.9.1/bin/node" "/home/blaze/.nvm/versions/node/v6.9.1/bin/npm" "update"
6155 error node v6.9.1
6156 error npm  v3.10.8
6157 error file sh
6158 error code ELIFECYCLE
6159 error errno ENOENT
6160 error syscall spawn
6161 error leowiki@1.0.2 install: `require-self`
6161 error spawn ENOENT
6162 error Failed at the leowiki@1.0.2 install script 'require-self'.
6162 error Make sure you have the latest version of node.js and npm installed.
6162 error If you do, this is most likely a problem with the leowiki package,
6162 error not with npm itself.
6162 error Tell the author that this fails on your system:
6162 error     require-self
6162 error You can get information on how to open an issue for this project with:
6162 error     npm bugs leowiki
6162 error Or if that isn't available, you can get their info via:
6162 error     npm owner ls leowiki
6162 error There is likely additional logging output above.
6163 verbose exit [ 1, true ]
```

**Comment by danPixl** [comment]
Appears to be an issue with the `require-self` package.

**Comment by danPixl** [comment]
Issue on my end, sorry for wasting time.
